### ISSUE TITLE
Support DNS resolution in the hub thing settings

### ISSUE THREAD

**Issue by LinqLover** [Skinah/EspMilightHub#11]
In the settings of the EspMilightHub thing, IWLT specify the DNS name of the milight hub rather than an IP address:

![image](https://user-images.githubusercontent.com/38782922/73167123-8fb00a00-40f7-11ea-8e59-d4801ef80458.png)

The problem with an IP address is that a) you need to look it manually and b) depending on your network configuration, the address might be volatile (for example, if you switch to another router).

If I enter the DNS name (`milight-hub`) instead, 

Would it be possible without big effort to support entering the DNS name here?

**Comment by Skinah** [comment]
I believe it works already, I just found a bug that was stopping any IP or dns name from working without the warning. Will upload a newer build tonight.
