### ISSUE TITLE
Maybe add option to not automatically clear the update topic on the ESP hub

### ISSUE THREAD

**Issue by RURon** [Skinah/EspMilightHub#6]
Hello there. From my experience with your binding (thanks for creating it btw!) seems to clear the update topic in the ESP hub settings. Is that true?

This gives me trouble as I also use the ESP hub to send remote commands from remotes that I use to control various other things, but not lamps. I also have a Milight lamp, so in the end I would love to use both your binding but also my way to connect to the update topic channel via MQTT binding in OpenHab2

So I would like to propose to leave the update topic setting alone, as it should not interfere with your binding (as long as the update and state topic are different, which should be pointed out in the documentation and could be tested and when both are the same you could log a warning/error in the OpenHab log?!).

**Comment by Skinah** [comment]
If you do not provide a hubIp to the binding it will not change the settings of the hub as I believe that is what is causing it to remove the topic you are setting up. It is not needed at all and is only there to help people setup the hub without making mistakes, but once working it can be removed.
